name: Tests
on:
  pull_request:
    branches:
      - master
jobs:
  unit_tests:
    name: unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-22.04, windows-2022]
        os: [ubuntu-22.04]
        rev: [v0.11.0]

    steps:
      - uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.rev }}

      - uses: ilammy/msvc-dev-cmd@v1
      - uses: leafo/gh-actions-lua@v12
        with:
          luaVersion: "5.1.5"

      - name: Install luarocks (Unix)
        if: ${{ matrix.os != 'windows-2022' }}
        uses: leafo/gh-actions-luarocks@v6

      - name: Install luarocks (Windows)
        if: ${{ matrix.os == 'windows-2022' }}
        run: |
          choco install luarocks

      - name: Copy telescope rockspec
        run: |
          curl https://raw.githubusercontent.com/nvim-telescope/telescope.nvim/refs/heads/master/telescope.nvim-scm-1.rockspec -o telescope.nvim-scm-1.rockspec

      - name: Install plugins
        run: |
          luarocks --version
          luarocks install telescope.nvim-scm-1.rockspec
          luarocks install --deps-only python-tools.nvim-0.2-0.rockspec
          luarocks install busted

      - name: Build
        env:
          CMAKE_PREFIX_PATH: ${{ github.workspace }}/.lua/
        run: |
          make develop
          # ls .lua/lib
          # cmake -S . -B build -DCMAKE_BUILD_TYPE=release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_FIND_DEBUG_MODE=ON -DLUA_INCLUDE_DIR=".lua/include" -DLUA_LIBRARIES=".lua/lib/liblua.a"
          # cmake --build build --config release

      - name: Run tests
        run: |
          make test
